spring:
  application:
    name: my-market
  datasource:
    url: jdbc:postgresql://localhost:5432/g139?currentSchema=market
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml