spring:
  application:
    name: my-market
  datasource:
    url: jdbc:postgresql://localhost:5432/g139?currentSchema=market
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}  # 30 минут в миллисекундах
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 7 дней в миллисекундах